import type { Metadata } from "next";
import { ThirdwebProvider } from "@/components/ThirdwebProvider";
import { Avalanche } from "@thirdweb-dev/chains";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Oracle",
  description: "Generated by create next app",
};

const testNet = {
  chainId: 1337,
  name: "TEST",
  chain:"TEST",
  rpc: ["http://127.0.0.1:8545"],
  nativeCurrency: {
    name: "ETH",
    symbol: "ETH",
    decimals: 18,
  },
  shortName: "eth",
  slug:"eth",
  testnet: true,
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white">
        <ThirdwebProvider
          activeChain={Avalanche}
          supportedChains={[Avalanche]}
          clientId="your-client-id"
        >
          {children}
        </ThirdwebProvider>
      </body>
    </html>
  );
}
